{
 "title": "1.SystemMonitoringProject Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "System Monitoring",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 16, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "disk_usage{job=\"system_monitor\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cpu_usage{job=\"system_monitor\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "memory_usage{job=\"system_monitor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU Usage Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 1, "y": 15 },
   "targets": [
    {
     "expr": "cpu_usage{job=\"system_monitor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Memory Usage Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 1, "y": 24 },
   "targets": [
    {
     "expr": "memory_usage{job=\"system_monitor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disk Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Disk Usage Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "disk_usage{job=\"system_monitor\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}